/* -*- C -*- */
/* translate.c */
/* erzeugt Freitag, 16. Februar 2024 15:42 (C) 2024 von Leander Jedamus */
/* modifiziert Freitag, 16. Februar 2024 16:44 von Leander Jedamus */

#include <stdio.h>

#include "gettext.h"

void translate(void) {
  printf("%s\n", _("Accessing a corrupted shared library"));
  printf("%s\n", _("Address already in use"));
  printf("%s\n", _("Address family not supported by protocol"));
  printf("%s\n", _("Address family not supported by protocol family"));
  printf("%s\n", _("Advertise error"));
  printf("%s\n", _("Argument list too long"));
  printf("%s\n", _("Attempting to link in too many shared libraries"));
  printf("%s\n", _("Attribute not found"));
  printf("%s\n", _("Authentication error"));
  printf("%s\n", _("Bad address"));
  printf("%s\n", _("Bad CPU type in executable"));
  printf("%s\n", _("Bad executable (or shared library)"));
  printf("%s\n", _("Bad file descriptor"));
  printf("%s\n", _("Bad font file format"));
  printf("%s\n", _("Bad message"));
  printf("%s\n", _("Bad procedure for program"));
  printf("%s\n", _("Block device required"));
  printf("%s\n", _("Broken pipe"));
  printf("%s\n", _("Can not access a needed shared library"));
  printf("%s\n", _("Cannot allocate memory"));
  printf("%s\n", _("Cannot assign requested address"));
  printf("%s\n", _("Cannot exec a shared library directly"));
  printf("%s\n", _("Cannot send after transport endpoint shutdown"));
  printf("%s\n", _("Can't assign requested address"));
  printf("%s\n", _("Can't send after socket shutdown"));
  printf("%s\n", _("Channel number out of range"));
  printf("%s\n", _("Communication error on send"));
  printf("%s\n", _("Connection refused"));
  printf("%s\n", _("Connection reset by peer"));
  printf("%s\n", _("Connection timed out"));
  printf("%s\n", _("Cross-device link"));
  printf("%s\n", _("Destination address required"));
  printf("%s\n", _("Device error"));
  printf("%s\n", _("Device not a stream"));
  printf("%s\n", _("Device not configured"));
  printf("%s\n", _("Device or resource busy"));
  printf("%s\n", _("Device power is off"));
  printf("%s\n", _("Directory not empty"));
  printf("%s\n", _("Disc quota exceeded"));
  printf("%s\n", _("Disk quota exceeded"));
  printf("%s\n", _("EMULTIHOP (Reserved)"));
  printf("%s\n", _("ENOLINK (Reserved)"));
  printf("%s\n", _("Exchange full"));
  printf("%s\n", _("Exec format error"));
  printf("%s\n", _("File descriptor in bad state"));
  printf("%s\n", _("File exists"));
  printf("%s\n", _("File name too long"));
  printf("%s\n", _("File too large"));
  printf("%s\n", _("Function not implemented"));
  printf("%s\n", _("Host is down"));
  printf("%s\n", _("Identifier removed"));
  printf("%s\n", _("Illegal byte sequence"));
  printf("%s\n", _("Illegal seek"));
  printf("%s\n", _("Inappropriate file type or format"));
  printf("%s\n", _("Inappropriate ioctl for device"));
  printf("%s\n", _("Input/output error"));
  printf("%s\n", _("Interface output queue is full"));
  printf("%s\n", _("Interrupted system call"));
  printf("%s\n", _("Interrupted system call should be restarted"));
  printf("%s\n", _("Invalid argument"));
  printf("%s\n", _("Invalid cross-device link"));
  printf("%s\n", _("Invalid exchange"));
  printf("%s\n", _("Invalid or incomplete multibyte or wide character"));
  printf("%s\n", _("Invalid request code"));
  printf("%s\n", _("Invalid request descriptor"));
  printf("%s\n", _("Invalid slot"));
  printf("%s\n", _("Is a directory"));
  printf("%s\n", _("Is a named type file"));
  printf("%s\n", _("Key has been revoked"));
  printf("%s\n", _("Key has expired"));
  printf("%s\n", _("Key was rejected by service"));
  printf("%s\n", _("Level 2 halted"));
  printf("%s\n", _("Level 2 not synchronized"));
  printf("%s\n", _("Level 3 halted"));
  printf("%s\n", _("Level 3 reset"));
  printf("%s\n", _(".lib section in a.out corrupted"));
  printf("%s\n", _("Link has been severed"));
  printf("%s\n", _("Link number out of range"));
  printf("%s\n", _("Machine is not on the network"));
  printf("%s\n", _("Malformed Mach-o file"));
  printf("%s\n", _("Memory page has hardware error"));
  printf("%s\n", _("Message too long"));
  printf("%s\n", _("Multihop attempted"));
  printf("%s\n", _("Name not unique on network"));
  printf("%s\n", _("Need authenticator"));
  printf("%s\n", _("Network dropped connection on reset"));
  printf("%s\n", _("Network is down"));
  printf("%s\n", _("Network is unreachable"));
  printf("%s\n", _("No anode"));
  printf("%s\n", _("No buffer space available"));
  printf("%s\n", _("No child processes"));
  printf("%s\n", _("No CSI structure available"));
  printf("%s\n", _("No data available"));
  printf("%s\n", _("No locks available"));
  printf("%s\n", _("No medium found"));
  printf("%s\n", _("No message available on STREAM"));
  printf("%s\n", _("No message of desired type"));
  printf("%s\n", _("No route to host"));
  printf("%s\n", _("No space left on device"));
  printf("%s\n", _("No STREAM resources"));
  printf("%s\n", _("No such device"));
  printf("%s\n", _("No such device or address"));
  printf("%s\n", _("No such file or directory"));
  printf("%s\n", _("No such process"));
  printf("%s\n", _("Not a directory"));
  printf("%s\n", _("Not a STREAM"));
  printf("%s\n", _("Not a XENIX named type file"));
  printf("%s\n", _("No XENIX semaphores available"));
  printf("%s\n", _("Numerical argument out of domain"));
  printf("%s\n", _("Numerical result out of range"));
  printf("%s\n", _("Object is remote"));
  printf("%s\n", _("Operation already in progress"));
  printf("%s\n", _("Operation canceled"));
  printf("%s\n", _("Operation not permitted"));
  printf("%s\n", _("Operation not possible due to RF-kill"));
  printf("%s\n", _("Operation not supported"));
  printf("%s\n", _("Operation not supported by device"));
  printf("%s\n", _("Operation not supported on socket"));
  printf("%s\n", _("Operation now in progress"));
  printf("%s\n", _("Operation timed out"));
  printf("%s\n", _("Out of streams resources"));
  printf("%s\n", _("Owner died"));
  printf("%s\n", _("Package not installed"));
  printf("%s\n", _("Permission denied"));
  printf("%s\n", _("Policy not found"));
  printf("%s\n", _("Previous owner died"));
  printf("%s\n", _("Program version wrong"));
  printf("%s\n", _("Protocol driver not attached"));
  printf("%s\n", _("Protocol error"));
  printf("%s\n", _("Protocol family not supported"));
  printf("%s\n", _("Protocol not available"));
  printf("%s\n", _("Protocol not supported"));
  printf("%s\n", _("Protocol wrong type for socket"));
  printf("%s\n", _("Read-only file system"));
  printf("%s\n", _("Remote address changed"));
  printf("%s\n", _("Remote I/O error"));
  printf("%s\n", _("Required key not available"));
  printf("%s\n", _("Resource busy"));
  printf("%s\n", _("Resource deadlock avoided"));
  printf("%s\n", _("Resource temporarily unavailable"));
  printf("%s\n", _("Result too large"));
  printf("%s\n", _("RFS specific error"));
  printf("%s\n", _("RPC prog. not avail"));
  printf("%s\n", _("RPC struct is bad"));
  printf("%s\n", _("RPC version wrong"));
  printf("%s\n", _("Shared library version mismatch"));
  printf("%s\n", _("Socket is already connected"));
  printf("%s\n", _("Socket is not connected"));
  printf("%s\n", _("Socket operation on non-socket"));
  printf("%s\n", _("Socket type not supported"));
  printf("%s\n", _("Software caused connection abort"));
  printf("%s\n", _("Srmount error"));
  printf("%s\n", _("Stale file handle"));
  printf("%s\n", _("Stale NFS file handle"));
  printf("%s\n", _("State not recoverable"));
  printf("%s\n", _("STREAM ioctl timeout"));
  printf("%s\n", _("Streams pipe error"));
  printf("%s\n", _("Structure needs cleaning"));
  printf("%s\n", _("Success"));
  printf("%s\n", _("Text file busy"));
  printf("%s\n", _("Timer expired"));
  printf("%s\n", _("Too many levels of remote in path"));
  printf("%s\n", _("Too many levels of symbolic links"));
  printf("%s\n", _("Too many links"));
  printf("%s\n", _("Too many open files"));
  printf("%s\n", _("Too many open files in system"));
  printf("%s\n", _("Too many processes"));
  printf("%s\n", _("Too many references: cannot splice"));
  printf("%s\n", _("Too many references: can't splice"));
  printf("%s\n", _("Too many users"));
  printf("%s\n", _("Transport endpoint is already connected"));
  printf("%s\n", _("Transport endpoint is not connected"));
  printf("%s\n", _("Undefined error: 0"));
  printf("%s\n", _("Unknown error: 107"));
  printf("%s\n", _("Unknown error: 133"));
  printf("%s\n", _("Unknown error 41"));
  printf("%s\n", _("Unknown error 58"));
  printf("%s\n", _("Value too large for defined data type"));
  printf("%s\n", _("Value too large to be stored in data type"));
  printf("%s\n", _("Wrong medium type"));
};

/* vim:set cindent ai sw=2: */

